#!/bin/sh

CHEF_DIR=`dirname $0`
if `hash readlink 2>&-`; then
    LINKED_EXE=`readlink $0`
    if [ -n "$LINKED_EXE" ]; then
        CHEF_DIR=`dirname $LINKED_EXE`
    fi
fi
ROOT_DIR=`dirname $CHEF_DIR`
echo "'$CHEF_DIR/chef' is deprecated. Please use '$ROOT_DIR/bin/chef' instead."
$ROOT_DIR/bin/chef $@
