<?php

// autoload_namespace.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'org\\bovigo\\vfs' => $baseDir . '/libs/mikey179/vfsStream/src/main/php',
);
