<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'MockProcessor' => $baseDir . '/src/test-objects/MockProcessor.php',
    'MockPluginLoader' => $baseDir . '/src/test-objects/MockPluginLoader.php',
    'MockPlugin' => $baseDir . '/src/test-objects/MockPlugin.php',
    'MockPieCrust' => $baseDir . '/src/test-objects/MockPieCrust.php',
    'MockPage' => $baseDir . '/src/test-objects/MockPage.php',
    'MockFormatter' => $baseDir . '/src/test-objects/MockFormatter.php',
    'MockFileSystem' => $baseDir . '/src/test-objects/MockFileSystem.php',
);
