<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'org\\bovigo\\vfs' => array($vendorDir . '/mikey179/vfsStream/src/main/php'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'StupidHttp_' => array($vendorDir . '/bolt80/stupidhttp/lib'),
    'PieCrust' => array($baseDir . '/src', $baseDir . '/tests/src'),
    'Netcarver\\Textile' => array($vendorDir . '/netcarver/textile/src'),
    'Mustache' => array($vendorDir . '/mustache/mustache/src'),
    'Michelf' => array($vendorDir . '/michelf/php-markdown'),
    'Log' => array($vendorDir . '/pear'),
    'Console' => array($vendorDir . '/pear'),
    'Benchmark_' => array($vendorDir . '/pear'),
);
