<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'org\\bovigo\\vfs' => $vendorDir . '/mikey179/vfsStream/src/main/php',
    'Twig_' => $vendorDir . '/twig/twig/lib/',
    'Symfony\\Component\\Yaml' => $vendorDir . '/symfony/yaml/',
    'StupidHttp_' => $vendorDir . '/bolt80/stupidhttp/lib',
    'PieCrust' => array($baseDir . '/src/', $baseDir . '/tests/src/'),
    'Log' => $baseDir . '/libs/pear',
    'Console' => $baseDir . '/libs/pear',
    'Benchmark_' => $baseDir . '/libs/pear',
);
