<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'GeSHi' => $baseDir . '/libs/geshi/geshi/geshi.php',
    'Mustache' => $baseDir . '/libs/mustache/mustache/Mustache.php',
    'MustacheException' => $baseDir . '/libs/mustache/mustache/Mustache.php',
    'MustacheLoader' => $baseDir . '/libs/mustache/mustache/MustacheLoader.php',
    'Textile' => $baseDir . '/libs/textile/textile/classTextile.php',
    'easyparse' => $baseDir . '/libs/lessphp/lessphp/lessify.inc.php',
    'lessc' => $baseDir . '/libs/lessphp/lessphp/lessc.inc.php',
    'lessify' => $baseDir . '/libs/lessphp/lessphp/lessify.inc.php',
    'nodecounter' => $baseDir . '/libs/lessphp/lessphp/lessify.inc.php',
    'tagparse' => $baseDir . '/libs/lessphp/lessphp/lessify.inc.php',
);
