<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'org\\bovigo\\vfs' => $vendorDir . '/mikey179/vfsStream/src/main/php',
    'Twig_' => $vendorDir . '/twig/twig/lib',
    'Symfony\\Component\\Yaml\\' => $vendorDir . '/symfony/yaml',
    'StupidHttp_' => $vendorDir . '/bolt80/stupidhttp/lib',
    'PieCrust' => array($baseDir . '/src', $baseDir . '/tests/src'),
    'Netcarver\\Textile' => $vendorDir . '/netcarver/textile/src',
    'Mustache' => $vendorDir . '/mustache/mustache/src',
    'Michelf' => $vendorDir . '/michelf/php-markdown',
    'Log' => $vendorDir . '/pear',
    'Console' => $vendorDir . '/pear',
    'Benchmark_' => $vendorDir . '/pear',
);
